# Site settings
title: My Homebrew Journal
email: chris.papazian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "beer" # the subpath of your site, e.g. /blog/
url: "http://cpapazian.github.io" # the base hostname & protocol for your site
twitter_username: snappy173
github_username:  cpapazian

# Build settings
markdown: kramdown
